### ISSUE TITLE
[Improvement] Launch screen

### ISSUE THREAD

**Issue by realgooseman** [elibroftw/google-keep-desktop-app#1]
Hi @elibroftw,

First of all, thanks for this. You're the only one maintaining such app I think.
I would suggest one improvement if you allow me : 

### **The white launch screen is quite annoying, especially at night** 
![Launch screen](https://github.com/elibroftw/google-keep-desktop-app/assets/64812183/88863c90-6b9c-4799-a39c-d97f36350875)

I think a workaround would be to change the launch screen theme to dark for dark Google Keep instances and the opposite for light instances. It would help with eye strain for the ones who like everything in dark mode. 

Or you could create a dark splash screen before the app loads, useless but would look even cleaner.

**Comment by elibroftw** [comment]
Pretty sure there's a bug in Tauri I reported in January regarding a white screen. There's nothing I can do about it and this app was started as a demo since it would obvious be better if the UI was cached. I'll ask around if it's possible to cache the UI.

It's also possible to hide the window and show it later but the plugin that takes care of restoring the windows position also unhides it.

**Comment by realgooseman** [comment]
I see, well thanks for the clarification. I'm curious to see how this project will progress. If you plan to keep maintaining and improving it of course.

I've found dozens of abandoned Keep desktop clients, but yours is the most active I found yet and there's no alternative lol.

**Comment by elibroftw** [comment]
Well yeah I made this a demo for a YouTube video of mine because keep desktop does not really exist or is built using electron. This solution isn't exactly ideal because it's just a wrapper but given more experience one could hack something out

**Comment by realgooseman** [comment]
A workaround would be to install WSA and sideload the Google Keep apk to have the Google Keep android app run on Windows, but yes nothing native and it sucks. The dream would be a UWP native client with WinUI 3.
